class URLs:
    auth_url = 'https://www.saucedemo.com/v1/index.html'
    inventory_url = 'https://www.saucedemo.com/v1/inventory.html'
    item1_url = 'https://www.saucedemo.com/v1/inventory-item.html?id=4'
    item2_url = 'https://www.saucedemo.com/v1/inventory-item.html?id=0'
    item3_url = 'https://www.saucedemo.com/v1/inventory-item.html?id=1'
    item4_url = 'https://www.saucedemo.com/v1/inventory-item.html?id=5'
    item5_url = 'https://www.saucedemo.com/v1/inventory-item.html?id=2'
    item6_url = 'https://www.saucedemo.com/v1/inventory-item.html?id=3'
    cart_url = 'https://www.saucedemo.com/v1/cart.html'
    checkout_step1_url = 'https://www.saucedemo.com/v1/checkout-step-one.html'
    checkout_step2_url = 'https://www.saucedemo.com/v1/checkout-step-two.html'
    checkout_complete_url = 'https://www.saucedemo.com/v1/checkout-complete.html'
    about_url = 'https://saucelabs.com/'